name: briout
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Version mise à jour pour la compatibilité

dependencies:
  flutter:
    sdk: flutter

  # Paquets de base et UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  pinput: ^4.0.0

  # Paquets pour la connexion/inscription
  country_picker: ^2.0.26
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  
  # Paquets pour la carte et la localisation
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  http: ^1.2.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

# Configuration pour les icônes de l'application
flutter_icons:
  android: "adaptive"
  ios: true
  image_path: "assets/icon/ic_launcher.png"
  adaptive_icon_background: "#0165FC"
  adaptive_icon_foreground: "assets/icon/ic_foreground.png"

# Configuration générale de Flutter
flutter:
  uses-material-design: true

  # Déclaration des assets (fichiers images, etc.)
  # En déclarant le dossier, vous n'avez pas besoin de lister chaque image.
  assets:
    - assets/images/
    - assets/icon/