// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Ri8YIX4c4j2A2bRAEfAPJQV7n6YwyE8',
    appId: '1:67521502419:web:b59d417dfcb479af96c826',
    messagingSenderId: '67521502419',
    projectId: 'briout-mt',
    authDomain: 'briout-mt.firebaseapp.com',
    storageBucket: 'briout-mt.firebasestorage.app',
    measurementId: 'G-NS9EB1EVEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcs49sQIu5TJVL-dZ7hasunMgeb66TEOk',
    appId: '1:67521502419:android:edce3966cafb4f9e96c826',
    messagingSenderId: '67521502419',
    projectId: 'briout-mt',
    storageBucket: 'briout-mt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASEqSZDbd8BqPezWaDh1T5g_yfQQHr5B8',
    appId: '1:67521502419:ios:3b29232d69f9285f96c826',
    messagingSenderId: '67521502419',
    projectId: 'briout-mt',
    storageBucket: 'briout-mt.firebasestorage.app',
    iosBundleId: 'com.example.briout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASEqSZDbd8BqPezWaDh1T5g_yfQQHr5B8',
    appId: '1:67521502419:ios:3b29232d69f9285f96c826',
    messagingSenderId: '67521502419',
    projectId: 'briout-mt',
    storageBucket: 'briout-mt.firebasestorage.app',
    iosBundleId: 'com.example.briout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0Ri8YIX4c4j2A2bRAEfAPJQV7n6YwyE8',
    appId: '1:67521502419:web:fb1583c0d74b2a8696c826',
    messagingSenderId: '67521502419',
    projectId: 'briout-mt',
    authDomain: 'briout-mt.firebaseapp.com',
    storageBucket: 'briout-mt.firebasestorage.app',
    measurementId: 'G-DMG3TRJB78',
  );
}
